#!/bin/bash
set -euo pipefail

# This is a githook dispatcher. It runs all executable scripts in 
# .githooks/$(basename "$0").d/

# Find the root of the git repository
GIT_ROOT=$(git rev-parse --show-toplevel)

HOOK_NAME=$(basename "$0")
HOOKS_DIR="$GIT_ROOT/.githooks/${HOOK_NAME}.d"

EXIT_CODE=0

if [ -d "$HOOKS_DIR" ]; then
    while read -r hook; do
        if [ -x "$hook" ]; then
            if ! "$hook"; then
                EXIT_CODE=1
            fi
        fi
    done < <(find "$HOOKS_DIR" -maxdepth 1 -type f)
fi

exit $EXIT_CODE
